import type { CourierRequestItem, FeedPost } from "./types";

// Placeholder data so the UI renders without the API. Swap for the real
// products/needs services once the unified feed endpoint exists.
export const MOCK_POSTS: FeedPost[] = [
  {
    id: "1",
    kind: "offer",
    title: "ক্লাস ৮-এর সব বই (সেট)",
    description: "গত বছরের সব বই, ভালো অবস্থায়। দুটো বইয়ে সামান্য দাগ আছে।",
    category: "books",
    condition: "good",
    area: "মিরপুর ১০",
    district: "ঢাকা",
    distanceKm: 1.2,
    author: { name: "রাকিব হাসান", verified: true, trust: 92 },
    images: [],
    postedAt: "২ ঘণ্টা আগে",
    requests: 3,
  },
  {
    id: "2",
    kind: "need",
    title: "পড়ার টেবিল দরকার",
    description: "ক্লাস ৯-এর একজন ছাত্রের জন্য ছোট একটা পড়ার টেবিল দরকার।",
    category: "furniture",
    condition: "used",
    area: "উত্তরা সেক্টর ৪",
    district: "ঢাকা",
    distanceKm: 3.4,
    author: { name: "সুমাইয়া আক্তার", verified: true, trust: 78 },
    images: [],
    postedAt: "৪ ঘণ্টা আগে",
    requests: 1,
  },
  {
    id: "3",
    kind: "offer",
    title: "নতুন খাতা ১২টি",
    description: "অতিরিক্ত কেনা হয়েছিল, একদম নতুন, ব্যবহার হয়নি।",
    category: "stationery",
    condition: "new",
    area: "ধানমন্ডি ১৫",
    district: "ঢাকা",
    distanceKm: 5.1,
    author: { name: "তানভীর আহমেদ", verified: false, trust: 40 },
    images: [],
    postedAt: "৬ ঘণ্টা আগে",
    requests: 0,
  },
  {
    id: "4",
    kind: "offer",
    title: "শিশুর শীতের জামা (২–৩ বছর)",
    description: "ধোয়া ও পরিষ্কার, ৫টি জামা।",
    category: "clothes",
    condition: "good",
    area: "আগ্রাবাদ",
    district: "চট্টগ্রাম",
    distanceKm: 214,
    author: { name: "নাজমা বেগম", verified: true, trust: 88 },
    images: [],
    postedAt: "১ দিন আগে",
    requests: 5,
  },
  {
    id: "5",
    kind: "need",
    title: "পুরনো ল্যাপটপ (পড়াশোনার জন্য)",
    description: "অনলাইন ক্লাসের জন্য যেকোনো চালু ল্যাপটপ হলেই চলবে।",
    category: "electronics",
    condition: "used",
    area: "জিন্দাবাজার",
    district: "সিলেট",
    distanceKm: 240,
    author: { name: "ফাহিম রহমান", verified: true, trust: 70 },
    images: [],
    postedAt: "১ দিন আগে",
    requests: 2,
  },
  {
    id: "6",
    kind: "offer",
    title: "কাঠের বুকশেলফ",
    description: "৪ তাক বিশিষ্ট, নিজে এসে নিতে হবে অথবা কুরিয়ারে।",
    category: "furniture",
    condition: "used",
    area: "কাজীপাড়া",
    district: "ঢাকা",
    distanceKm: 1.9,
    author: { name: "মাহবুব আলম", verified: true, trust: 95 },
    images: [],
    postedAt: "২ দিন আগে",
    requests: 4,
  },
  {
    id: "7",
    kind: "offer",
    title: "খেলনা গাড়ি ও ব্লক সেট",
    description: "বাচ্চারা বড় হয়ে গেছে, খেলনাগুলো ভালো আছে।",
    category: "kids",
    condition: "good",
    area: "সদর",
    district: "রাজশাহী",
    distanceKm: 250,
    author: { name: "শিউলি খাতুন", verified: false, trust: 52 },
    images: [],
    postedAt: "২ দিন আগে",
    requests: 0,
  },
  {
    id: "8",
    kind: "need",
    title: "গল্পের বই — শিশুদের জন্য",
    description: "এতিমখানার লাইব্রেরির জন্য যেকোনো গল্পের বই।",
    category: "books",
    condition: "used",
    area: "মিরপুর ১১",
    district: "ঢাকা",
    distanceKm: 2.2,
    author: { name: "আলোর পথে ফাউন্ডেশন", verified: true, trust: 99 },
    images: [],
    postedAt: "৩ দিন আগে",
    requests: 7,
  },
];

export const MOCK_COURIER: CourierRequestItem[] = [
  {
    id: "c1",
    item: "ক্লাস ৮-এর সব বই (সেট)",
    category: "books",
    giver: { name: "রাকিব হাসান", phone: "01711-000001", address: "মিরপুর ১০, ঢাকা" },
    receiver: { name: "ফাহিম রহমান", phone: "01811-000002", address: "জিন্দাবাজার, সিলেট" },
    weightKg: 3,
    charge: 130,
    status: "pending",
    createdAt: "আজ, ১০:২০",
  },
  {
    id: "c2",
    item: "শিশুর শীতের জামা",
    category: "clothes",
    giver: { name: "নাজমা বেগম", phone: "01911-000003", address: "আগ্রাবাদ, চট্টগ্রাম" },
    receiver: { name: "সুমাইয়া আক্তার", phone: "01611-000004", address: "উত্তরা সেক্টর ৪, ঢাকা" },
    weightKg: 1,
    charge: 110,
    status: "pending",
    createdAt: "গতকাল, ১৬:০৫",
  },
  {
    id: "c3",
    item: "কাঠের বুকশেলফ",
    category: "furniture",
    giver: { name: "মাহবুব আলম", phone: "01511-000005", address: "কাজীপাড়া, ঢাকা" },
    receiver: { name: "তানভীর আহমেদ", phone: "01311-000006", address: "ধানমন্ডি ১৫, ঢাকা" },
    weightKg: 12,
    charge: 250,
    status: "confirmed",
    createdAt: "২ দিন আগে",
  },
];

// Shown in ad slots until a real Ad Manager network code is configured.
export const MOCK_ADS = [
  {
    id: "a1",
    brand: "স্থানীয় বইয়ের দোকান",
    headline: "ব্যবহৃত বই কিনুন অর্ধেক দামে",
    body: "ঢাকার সব এলাকায় ফ্রি হোম ডেলিভারি।",
    cta: "দেখুন",
  },
  {
    id: "a2",
    brand: "শিক্ষা অ্যাপ",
    headline: "ঘরে বসে পড়াশোনা — ৭ দিন ফ্রি",
    body: "এসএসসি ও এইচএসসি-র সব বিষয়।",
    cta: "ট্রাই করুন",
  },
];
