import { getSupabaseClient } from "../client";
import type { Notification } from "@reusedo/validation";

export class NotificationRepository {
  private getClient = (useServiceRole = false) => getSupabaseClient(useServiceRole);

  async createNotification(
    data: Omit<Notification, "id" | "created_at" | "updated_at" | "is_read" | "is_archived">,
  ): Promise<Notification> {
    const supabase = this.getClient(true); // Notifications are typically generated by the system

    const { data: notification, error } = await supabase
      .from("notifications")
      .insert({
        ...data,
      })
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to create notification: ${error.message}`);
    }

    return notification as Notification;
  }

  async getNotifications(
    userId: string,
    options: {
      limit?: number;
      offset?: number;
      type?: string;
      is_read?: boolean;
    } = {},
  ): Promise<{ data: Notification[]; count: number }> {
    const supabase = this.getClient();
    let query = supabase
      .from("notifications")
      .select("*", { count: "exact" })
      .eq("user_id", userId)
      .order("created_at", { ascending: false });

    if (options.type) {
      query = query.eq("type", options.type);
    }
    if (options.is_read !== undefined) {
      query = query.eq("is_read", options.is_read);
    }

    if (options.limit) {
      query = query.limit(options.limit);
      if (options.offset) {
        query = query.range(options.offset, options.offset + options.limit - 1);
      }
    }

    const { data, error, count } = await query;

    if (error) {
      throw new Error(`Failed to fetch notifications: ${error.message}`);
    }

    return { data: data as Notification[], count: count || 0 };
  }

  async getUnreadCount(userId: string): Promise<number> {
    const supabase = this.getClient();
    const { count, error } = await supabase
      .from("notifications")
      .select("*", { count: "exact", head: true })
      .eq("user_id", userId)
      .eq("is_read", false);

    if (error) {
      throw new Error(`Failed to fetch unread count: ${error.message}`);
    }

    return count || 0;
  }

  async markAsRead(userId: string, notificationId: string): Promise<Notification> {
    const supabase = this.getClient();
    const { data, error } = await supabase
      .from("notifications")
      .update({ is_read: true })
      .eq("user_id", userId)
      .eq("id", notificationId)
      .select()
      .single();

    if (error) {
      throw new Error(`Failed to mark notification as read: ${error.message}`);
    }

    return data as Notification;
  }

  async markAllAsRead(userId: string): Promise<void> {
    const supabase = this.getClient();
    const { error } = await supabase
      .from("notifications")
      .update({ is_read: true })
      .eq("user_id", userId)
      .eq("is_read", false);

    if (error) {
      throw new Error(`Failed to mark all notifications as read: ${error.message}`);
    }
  }

  async deleteNotification(userId: string, notificationId: string): Promise<void> {
    const supabase = this.getClient();
    const { error } = await supabase
      .from("notifications")
      .delete()
      .eq("user_id", userId)
      .eq("id", notificationId);

    if (error) {
      throw new Error(`Failed to delete notification: ${error.message}`);
    }
  }

  // FCM Tokens
  async registerFCMToken(userId: string, token: string, deviceInfo?: string): Promise<void> {
    const supabase = this.getClient();
    
    // Using upsert since (user_id, token) is unique
    const { error } = await supabase
      .from("fcm_tokens")
      .upsert({ user_id: userId, token, device_info: deviceInfo }, { onConflict: "user_id,token" });

    if (error) {
      throw new Error(`Failed to register FCM token: ${error.message}`);
    }
  }

  async getUserFCMTokens(userId: string): Promise<string[]> {
    const supabase = this.getClient(true); // We might need this from the service layer to send pushes
    const { data, error } = await supabase
      .from("fcm_tokens")
      .select("token")
      .eq("user_id", userId);

    if (error) {
      throw new Error(`Failed to fetch FCM tokens: ${error.message}`);
    }

    return data.map((row) => row.token);
  }

  async removeFCMToken(userId: string, token: string): Promise<void> {
    const supabase = this.getClient();
    const { error } = await supabase
      .from("fcm_tokens")
      .delete()
      .eq("user_id", userId)
      .eq("token", token);

    if (error) {
      throw new Error(`Failed to remove FCM token: ${error.message}`);
    }
  }
}
